### ISSUE TITLE
Hardware details in training

### ISSUE THREAD

**Issue by prochalo** [ml-research/NeSyConceptLearner#1]
May I ask you about the hardware you used in training for the NeSy ConceptLearner part and the whole project, such as which GPU, how many GPUs you used and the training time?

**Comment by wolfstam** [comment]
Sorry for my late reply. Each seed was trained on a single gpu, though you can of course run several seeds in parallel on one gpu. 
The GPU was a Tesla V100 SXM3 32GB. 
I don't fully remember the training time. It depends on whether you train via XIL or not. it might have been under an hour for 100 epochs, but don't pin me down on this ;)

**Comment by prochalo** [comment]
Thank you very much for this information ;)
